# This is a config for E2B sandbox template.
# You can use template ID (hys7vticlgb8dqqowsp2) or template name (vibe-next-testing) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-next-testing") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-next-testing") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-next-testing')

team_id = "73d238d3-b2d9-4b04-976d-55e92b94270c"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-next-testing"
template_id = "hys7vticlgb8dqqowsp2"
