import { Sandbox } from "@e2b/code-interpreter"
import { AgentResult, TextMessage } from "@inngest/agent-kit";

export async function getSandbox(sandboxId: string) {
    const sandbox = await Sandbox.connect(sandboxId)
    return sandbox;
}

export function lastAssistantTextMessageContent(result: AgentResult) {
    const lastAssistantTextMessageIndex = result.output.findLastIndex(
        (message) => message.role === "assistant", // "assistant" means generated by AI, "user" means generated by user (human)
    );

    const message = result.output[lastAssistantTextMessageIndex] as 
        | TextMessage
        | undefined;

    return message?.content
        ? typeof message.content === "string"
          ? message.content 
          // For long outputs, streaming responses, or structured formats, the API may break the text into multiple pieces. So here, we add them all to be a string
          : message.content.map((c) => c.text).join("") 
        : undefined;
};